
variable "name" {
  description = "The friendly name for the SNS platform application"
  type        = string
}

variable "platform" {
  type        = string
  description = "The platform that the app is registered with. See Platform for supported platforms like 'APNS' 'GCM'"
  default     = ""
}

variable "key" {
  type        = string
  default     = ""
  description = "Application Platform credential. See Credential for type of credential required for platform. The value of this attribute when stored into the Terraform state is only a hash of the real value, so therefore it is not practical to use this as an attribute for other resources"
}

variable "certificate" {
  type        = string
  default     = null
  description = "application Platform principal. See Principal for type of principal required for platform. The value of this attribute when stored into the Terraform state is only a hash of the real value, so therefore it is not practical to use this as an attribute for other resources"
}

variable "event_delivery_failure_topic_arn" {
  type        = string
  default     = null
  description = "SNS Topic triggered when a delivery to any of the platform endpoints associated with your platform application encounters a permanent failure."
}

variable "event_endpoint_created_topic_arn" {
  type        = string
  default     = null
  description = "SNS Topic triggered when a new platform endpoint is added to your platform application."
}

variable "event_endpoint_deleted_topic_arn" {
  type        = string
  default     = null
  description = "SNS Topic triggered when an existing platform endpoint is deleted from your platform application."
}

variable "event_endpoint_updated_topic_arn" {
  type        = string
  default     = null
  description = " SNS Topic triggered when an existing platform endpoint is changed from your platform application."
}

variable "failure_feedback_role_arn" {
  type        = string
  default     = null
  description = "The IAM role permitted to receive failure feedback for this application."
}

variable "platform_principal" {
  type        = string
  default     = null
  description = "Application Platform principal. See Principal for type of principal required for platform. The value of this attribute when stored into the Terraform state is only a hash of the real value, so therefore it is not practical to use this as an attribute for other resources."
}

variable "success_feedback_role_arn" {
  type        = string
  default     = null
  description = "The IAM role permitted to receive success feedback for this application."
}

variable "success_feedback_sample_rate" {
  type        = string
  default     = 100
  description = "The percentage of success to sample (0-100)"
}

variable "topic_name" {
  type        = string
  default     = null
  description = "The friendly name for the SNS topic. By default generated by Terraform."
}

variable "name_prefix" {
  type        = string
  default     = null
  description = "The friendly name for the SNS topic. Conflicts with name."
}

variable "display_name" {
  type        = string
  default     = null
  description = "The display name for the SNS topic."
}

variable "policy" {
  type        = string
  default     = null
  description = "The fully-formed AWS policy as JSON. For more information about building AWS IAM policy documents with Terraform."
}

variable "delivery_policy" {
  type        = string
  default     = null
  description = "The SNS delivery policy."
}
variable "topic_name_prefix" {
  type        = string
  default     = null
  description = "The friendly name for the SNS topic. Conflicts with name."
}

variable "application_success_feedback_role_arn" {
  type        = string
  default     = null
  description = "The IAM role permitted to receive success feedback for this topic."
}

variable "application_success_feedback_sample_rate" {
  type        = string
  default     = null
  description = "Percentage of success to sample."
}

variable "application_failure_feedback_role_arn" {
  type        = string
  default     = null
  description = "IAM role for failure feedback."
}

variable "http_success_feedback_role_arn" {
  type        = string
  default     = null
  description = "The IAM role permitted to receive success feedback for this topic."
}

variable "http_success_feedback_sample_rate" {
  type        = string
  default     = null
  description = "Percentage of success to sample."
}

variable "http_failure_feedback_role_arn" {
  type        = string
  default     = null
  description = "IAM role for failure feedback."
}

variable "kms_master_key_id" {
  type        = string
  default     = null
  description = "The ID of an AWS-managed customer master key (CMK) for Amazon SNS or a custom CMK. For more information."
}

variable "lambda_success_feedback_role_arn" {
  type        = string
  default     = null
  description = "The IAM role permitted to receive success feedback for this topic."
}

variable "lambda_success_feedback_sample_rate" {
  type        = string
  default     = null
  description = "Percentage of success to sample."
}

variable "lambda_failure_feedback_role_arn" {
  type        = string
  default     = null
  description = "IAM role for failure feedback."
}

variable "sqs_success_feedback_role_arn" {
  type        = string
  default     = null
  description = "The IAM role permitted to receive success feedback for this topic."
}

variable "sqs_success_feedback_sample_rate" {
  type        = string
  default     = null
  description = "Percentage of success to sample."
}

variable "sqs_failure_feedback_role_arn" {
  type        = string
  default     = null
  description = "IAM role for failure feedback."
}